[profile.default]
solc_version = "0.8.22"
evm_version = "paris"

[fmt]
bracket_spacing = true
line_length = 120
tab_width = 4

[rpc_endpoints]
# All available network keywords:
# https://github.com/foundry-rs/forge-std/blob/ff4bf7db008d096ea5a657f2c20516182252a3ed/src/StdCheats.sol#L255-L271
optimism = "${OPTIMISM_WEB3_ENDPOINT_ARCHIVE}"
optimism-goerli = "${OPTIMISM_GOERLI_WEB3_ENDPOINT_ARCHIVE}"

[invariant]
call_override = false  # Override calls
runs          = 50     # The number of times to run the invariant tests
depth         = 200    # The number of calls to make in the invariant tests
fail_on_revert = true   # Fail the test if the contract reverts
